version: '3.1'
services:
  mongo-server:
    image: mongo:latest
    container_name: mongo-server
    #command: --auth
    restart: always
    volumes:
     - ./data/:/data/db
    ports:
     - 27017:27017
networks:
  default:
    external:
      name: ga-tech

# CLI Access:
# docker-compose run --rm mongo-server mongo --host mongo-server
